import 'package:get/get.dart';
class localstring extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_Us':{
      'Welcome':"Welcome",
      'Welcome Home':"Welcome Home",
      'email':"Email",
      'password':"Password",
      'login':"Login",
      'Setting':"Setting",
       'Home':"Home",
       'wallet':"wallet",
       'Orders':"Orders",
       'Make an order':"Make an order",
       'Contact us':"Contact us",
       'About us':"About us",
       'Log Out':"Log Out",
       'My Orders':"My Orders",
       'Current Order':"Current Order",
       'Order history':"Order history",
       'Track progress':"Track progress",
       'Confirm cancellation':"Confirm cancellation",
       'Confirm if you want to cancel this order':"Confirm if you want to cancel this order",
       'Confirm':"Confirm",
       'I changed my mind':"I changed my mind",
       'Driver was late':"Driver was late",
       'The order was wrong':"The order was wrong",
       'Some other reason':"Some other reason",
       'Enter a reason for canceling the order':"Enter a reason for canceling the order",
       'Cancel order':"Cancel order",
       'Delivery completed':"Delivery completed",
       'Before we conclude please finalize all required parts on this form':"Before we conclude please finalize all required parts on this form",
       'Payment':"Payment",
       'You have concluded all your Payment You have Br. remaining in payment ':"Paid? You have concluded all your Payment You have Br. remaining in payment",
       'Please check to verify if all packages have arrived':"Please check to verify if all packages have arrived",
       'All packages have arrived':"All packages have arrived",
       'Verified scan':"Verified scan",
       'Scan Qr code':"Scan Qr code",
       'You don\'t have any pending order.To make an order click the button below.':"You don\'t have any pending order.To make an order click the button below.",
       'Status':"Status",
       'Delivery Items':"Delivery Items",
       'Pick up detail':"Pick up detail",
       'Floor':"Floor",
       'with an elevator':"with an elevator",
       'With no elevator':"With no elevator",
       'Destination detail:':"Destination detail:",
       'Payment information:':"Payment information:",
       'Br.':"Br.",
       'Paid':"Paid",
       'All paid':"All paid",
       'not yet paid':"not yet paid",
       'There are no past orders in your history.':"There are no past orders in your history.",
       'Profile':"Profile",
       'Your profile info':"Your profile info",
       'Enter a valid first name':"Enter a valid first name",
       'Enter a valid last name':"Enter a valid last name",
       'Enter a valid phone number':"Enter a valid phone number",
       'Success!':"Success!",
       'Sorry, an error occured, try again later':"Sorry, an error occured, try again later",
       'Edit data':"Edit data",
       'Write your name':"Write your name",
       'Name':"Name",
       'Enter your email so we can reach you':"Enter your email so we can reach you",
       'your email':"your email",
       'write the Subject':"write the Subject",
       'Subject':"Subject",
       'What can we help you with':"What can we help you with",
       'write your message here':"write your message here",
       'Send':"Send",
       'Set Address and Pickup time':"Set Address and Pickup time",
       'Search by location':"Search by location",
       'Sorry, no luck':"Sorry, no luck",
       'Pick custom location':"Pick custom location",
       'pick':"pick",
       'Select a custom pick up location':"Slect a custom pick up location",
       'Set the Date of pick up':"Set the Date of pick up",
       'Next':"Next",
       'Select a destination location':"Select a destination location",
       'Set a Pickup date to proceed':"Set a Pickup date to proceed",
       'Select a destination location and a Pickup date':"Select a destination location and a Pickup date",
       'Submit':"Submit",
       'The total Distance is':"The total Distance is",
       'The total Duration of delivery is':"The total Duration of delivery is",
       'seconds':"seconds",
       'Your Balance':"Your Balance",
       'Your Card':"Your Card",
       'Deposit':"Deposit",
       'Latest spendings':"Latest spendings",
       'Deposit to wallet':"Deposit to wallet",
       'Buy card':"Buy card",
       'How would you like to Deposit?':"How would you like to Deposit?",
       'You can choose to deposit to your wallet directly, or buy our van-card for a lesser fee':"You can choose to deposit to your wallet directly, or buy our van-card for a lesser fee",
       'Account Holder':"Account Holder",
       'Expiration Date':"Expiration Date",
       'Verify Email':"Verify Email",
       'A verification email has been sent to this email address':"A verification email has been sent to this email address",
       'Resend Email':"Resend Email",
       'Cancel':"Cancel",
       'Finish up with your payment':"Finish up with your payment",
       'Price':"Price",
       'Transport Cost':"Transport Cost",
       'Packaging Cost':"Packaging Cost",
       'Service charge with tax:':"Service charge with tax:",
       'How do you want to pay':"How do you want to pay",
       'Pay from my wallet':"Pay from my wallet",
       'Pay on Pick Up':"Pay on Pick Up",
       'Use Van it card':"Use Van it card",
       'VAN it':"VAN it",
       'Enter Passcode':"Enter Passcode",
       'Delete':"Delete",
       'Which service do you require?':"Which service do you require?",
       'home':"home",
       'Home Moving':"Home Moving",
       'furniture':"furniture",
       'Furniture Move':"Furniture Move",
       'company':"company",
       'Company Move':"Company Move",
       'special':"special",
       'Special Move':"Special Move",
       'Boxes':"Boxes",
       'Chair':"Chair",
       'Table':"Table",
       'Bed':"Bed",
       'Bag':"Bag",
       'Small':"Small",
       'Medium':"Medium",
       'Large':"Large",
       'Huge':"Huge",
       'Box':"Box",
       'Sofa':"Sofa",
       'Book Shelf':"Book Shelf",
       'Medium house package':"Medium house package",
       'Sofa set':"Sofa set",
       'Small house package':"Small house package",
       'Vehicle: Mini-van':"Vehicle: Mini-van",
       'Vehicle: Isuzu medium sized':"Vehicle: Isuzu medium sized",
       'Large house package':"Large house package",
       'Vehicle: Enclosed Isuzu FSR':"Vehicle: Enclosed Isuzu FSR",
       'Huge house package':"Huge house package",
       'Vehicle: Iveco':"Vehicle: Iveco",
       'Home moving':"Home moving",
       'What other items did we miss':"What other items did we miss",
       'Other non-listed Items':"Other non-listed Items",
        'Has elevetor':"Has elevetor",
      'What floor is the package at the Starting location?':"What floor is the package at the Starting location?",
       'What floor is the package at Destination?':"What floor is the package at Destination?",
      'Proceed':"Proceed",
      'Vehicle: Mini-van ':"Vehicle: Mini-van ",
      'Vehicle: Enclosed Isuzu FSR ':"Vehicle: Enclosed Isuzu FSR ",
      // ignore: equal_keys_in_map
      'Set the Date of pick up':"Set the Date of pick up",
      // ignore: equal_keys_in_map
      'Next':"Next",
      // ignore: equal_keys_in_map
      'Select a destination location':"Select a destination location",
      // ignore: equal_keys_in_map
      'Set a Pickup date to proceed':"Set a Pickup date to proceed",
      'Select a destination location and a Pickup date ':"Select a destination location and a Pickup date ",
      'Order':"Order",
      'Deposit to your wallet':"Deposit to your wallet",
      'Through which bank and their service do you like to complete the payment.':"Through which bank and their service do you like to complete the payment.",
      'We need your legal name for verification purposes':"We need your legal name for verification purposes",
      'How much would you like to deposit? *':"How much would you like to deposit? *",
      'First name *':"First name *",
      'Middle name *':"Middle name *",
      'Last name *':"Last name *",
      '1000 - 100,000 br.':"1000 - 100,000 br.",
      'What is your legal First name?':"What is your legal First name?",
      'What is your legal Middle name?':"What is your legal Middle name?",
      'What is your legal last name?':"What is your legal last name?",
      'Enter a valid Amount to be deposited':"Enter a valid Amount to be deposited",
      'Enter a Valid legal name':"Enter a Valid legal name",
      "**Follow all the instructions below.":"**Follow all the instructions below.",
      'We are not responsible for any inconviniences if the instructions are incorrectly followed**':"We are not responsible for any inconviniences if the instructions are incorrectly followed**",
      '1) Choose any method Namely Manual/branch, Mobile banking or CBE birr to deposit/transfer.':"1) Choose any method Namely Manual/branch, Mobile banking or CBE birr to deposit/transfer.",
      '2) Deposit/transfer':"2) Deposit/transfer",
      'to account ':"to account ",
      '3) On the deposit form use the code below as a **Reason** this is very important.':"3) On the deposit form use the code below as a **Reason** this is very important.",
      '4) Your Account will be updated to the deposited amount within the next 12 hours.':"4) Your Account will be updated to the deposited amount within the next 12 hours.",
      '5) The code is':"5) The code is",
      'use this as Reason.':"use this as Reason.",
      'Beware of Capitalization of the code.':"Beware of Capitalization of the code.",
      'Hai This Is Full Screen Dialog':"Hai This Is Full Screen Dialog",
      'DISMISS':"DISMISS",
      'Your wallet':"Your wallet",
      'An amount of ':"An amount of ",
      ' Br. will be deducted from your wallet':" Br. will be deducted from your wallet",
      'Agree to the terms of service':"Agree to the terms of service",
      'Pay':"Pay",
      'Read this before you pay!':"Read this before you pay!",
      'I have read and agree to the Terms':"I have read and agree to the Terms",
      '1. Any change in Order or cancelation of the order should be done 4 hours prior to delivery We are not responsible for any misunderstanding after this set time In the event of such changes after the order a calculated price will be deducted from your van it account':"1. Any change in Order or cancelation of the order should be done 4 hours prior to delivery We are not responsible for any misunderstanding after this set time In the event of such changes after the order a calculated price will be deducted from your van it account",
      'Finish your order by agreeing to these terms':"Finish your order by agreeing to these terms",
      'Account holder: ':"Account holder: ",
      'Your credits: ':"Your credits: ",
      'Enter the name on your card':"Enter the name on your card",
      'Full name':"Full name",
      'What is the name on your card':"What is the name on your card",
      'The PIN':"The PIN",
      'Enter the PIN':"Enter the PIN",
      'the pin is a 4 digit number':"the pin is a 4 digit number",
      'Transaction completed':"Transaction completed",
      '10000 Br. Credit Card for just 8,500 Br.':"10000 Br. Credit Card for just 8,500 Br.",
      '30,000 Br. Credit Card for just 24,000 Br.':"30,000 Br. Credit Card for just 24,000 Br.",
      '50,000 Br. Credit Card for just 40,000 Br.':"50,000 Br. Credit Card for just 40,000 Br.",
      '100,000 Br. Credit Card for just 80,000 Br.':"100,000 Br. Credit Card for just 80,000 Br.",
      'Manual Pick-up':"Manual Pick-up",
      'Go to wallet to deposit':"Go to wallet to deposit",
      'Finish':"Finish",
      '1. You must have amount of at least 1000 br. deposited in your Van wallet to request an order.':"1. You must have amount of at least 1000 br. deposited in your Van wallet to request an order.",
      '- this amount will be reduced up on payment':"- this amount will be reduced up on payment",
      '2. You must Pay the required Amount in full upon pickup.':"2. You must Pay the required Amount in full upon pickup.",
      '3. All payments should be done on time as agreed upon.':"3. All payments should be done on time as agreed upon.",
      '4. Any change in Order or cancelation of the order should be done 4 hours prior to delivery.':"4. Any change in Order or cancelation of the order should be done 4 hours prior to delivery.",
      ' - We are not responsible for any misunderstanding after this set time':" - We are not responsible for any misunderstanding after this set time",
      ' - In the event of such changes after the order a calculated price will be deducted from your van it account':" - In the event of such changes after the order a calculated price will be deducted from your van it account",
      '5. Should there be any failure in payment':"5. Should there be any failure in payment",
      ' - Items to be delivered will be transported to our stores until further notice':" - Items to be delivered will be transported to our stores until further notice",
      ' - There will be an automatic freezing of the account and all the assets.':" - There will be an automatic freezing of the account and all the assets.",
      ' - Any amount remaining in the wallet will be frozen until further notice.':" - Any amount remaining in the wallet will be frozen until further notice.",
      ' - An extended payment window will be provided, this will be the final extended date to be provided.':" - An extended payment window will be provided, this will be the final extended date to be provided.",
      ' 6. If the above agreement is not honered Van-it team will be forced to persue any legal action that would be deemed necessary':" 6. If the above agreement is not honered Van-it team will be forced to persue any legal action that would be deemed necessary",
      'Contact Us':"Contact Us",
      'Please check your connection':"Please check your connection",
      'Reset passcode':"Reset passcode",
      'Passcode reset is a non-secure operation! Are you sure want to reset?':"Passcode reset is a non-secure operation! Are you sure want to reset?",
      'I proceed':"I proceed",
      'Change Password':"Change Password",
      'Enter the current Passcode':"Enter the current Passcode",
      'Enter a new Passcode':"Enter a new Passcode",
      'Settings':"Settings",
      'Continue':"Continue",
      'Furniture moving':"Furniture moving",
      'Furniture less than 2 by 2 meters ':"Furniture less than 2 by 2 meters ",
      'Vehicles included: Mini-Isuzu ':"Vehicles included: Mini-Isuzu ",
      'Furniture less than 4 by 2 meters':"Furniture less than 4 by 2 meters",
      'Furniture less than 5 by 3 meters':"Furniture less than 5 by 3 meters",
      'Mini van':"Mini van",
      'Isuzu':"Isuzu",
      'Isuzu FSR':"Isuzu FSR",
      'Company moving':"Company moving",
      'Small company package':"Small company package",
      'This package includes upto:':"This package includes upto:",
      'Office desk':"Office desk",
      'Book shelf':"Book shelf",
      'Fragile electronics':"Fragile electronics",
      'Chairs':"Chairs",
      'Latest deposits':"Latest deposits",
      'Amount:':"Amount:",
      '\n\n Your Card':"'\n\n Your Card'",
      'Status:':"Status:",
      'Distance is: ':"Distance is: ",
      'The package will arive in:':"The package will arive in:",





    },
    'Am_Et':{
      'Welcome':"እንኳን ደህና መጣህ",
      'Status:':"ሁኔታ:",
      '\n\n Your Card':"የእርስዎ ካርድ",
      'Book shelf':"የመጽሐፍ መደርደሪያ",
      'The package will arive in:':"ጥቅሉ በሚከተለው ውስጥ ይመጣል:",
      'Amount:':"መጠን፡",
      'Distance is: ':"ርቀቱ፡ ",
      'Latest deposits':"የቅርብ ጊዜ ተቀማጭ ገንዘብ",
  'Office desk':"የቢሮ ጠረጴዛ",
      'Chairs':"ወንበሮች",
      'Fragile electronics':"ተበላሽ ኤሌክትሮኒክስ",
      'Company moving':"ኩባንያ የሚንቀሳቀስ",
      'This package includes upto:':"ይህ ጥቅል የሚከተሉትን ያካትታል:",
      'Small company package':"የአነስተኛ ኩባንያ ጥቅል",
      'Furniture moving':"የቤት ዕቃዎች መንቀሳቀስ",
      'Mini van':"ሚኒ ቫን",
      'Isuzu':"አይሱዙ",
      'Isuzu FSR':"ኢሱዙ ኤፍኤስአር",
      'Furniture less than 5 by 3 meters':"ከ5 በ3 ሜትር ያነሱ የቤት ዕቃዎች",
      'Furniture less than 4 by 2 meters':"ከ4 በ2 ሜትር ያነሱ የቤት ዕቃዎች",

      'Furniture less than 2 by 2 meters ':"ከ 2 በ 2 ሜትር ያነሰ የቤት እቃዎች ",
      'Vehicles included: Mini-Isuzu ':"የተካተቱት ተሽከርካሪዎች፡ ሚኒ-ኢሱዙ",
      'Welcome Home':"እንኳን ደህና መጣህ",
      'Continue':"ቀጥል",
      'email':"ኢሜይል",
      'password':"የይለፍ ቃል",
      'login':"ግባ",
      'Setting':"ቅንብር",
      'Home':"ቤት",
      'wallet':"የኪስ ቦርሳ",
       'Orders':"ትዕዛዞች",
       'Make an order':"ትእዛዝ ስጥ",
       'Contact us':"አግኙን",
       'About us':"ስለ እኛ",
       'Log Out':"ውጣ",
        'My Orders':"የእኔ ትዕዛዞች",
       'Current Order':"የአሁኑ ትዕዛዝ",
       'Order history':"የትዕዛዝ ታሪክ",
       'Track progress':"እድገትን ይከታተሉ",
       'Confirm cancellation':"መሰረዙን ያረጋግጡ",
       'Confirm if you want to cancel this order':"ይህን ትዕዛዝ መሰረዝ ከፈለጉ ያረጋግጡ",
       'Confirm':"አረጋግጥ",
       'I changed my mind':"ሃሳቤን ለውጫለሁ",
       'Driver was late':"ሹፌሩ አርፍዶ ነበር።",
       'The order was wrong':"ትዕዛዙ ስህተት ነበር።",
       'Some other reason':"ሌላ ምክንያት",
       'Enter a reason for canceling the order':"ትዕዛዙን ለመሰረዝ ምክንያት ያስገቡ",
       'Cancel order':"ትዕዛዝ ሰርዝ",
       'Delivery completed':"ማቅረቡ ተጠናቅቋል",
       'Before we conclude please finalize all required parts on this form':"ከመጠናቀቁ በፊት እባክዎ በዚህ ቅጽ ላይ ሁሉንም አስፈላጊ ክፍሎች ያጠናቅቁ",
       'Payment':"ክፍያ",
       'You have concluded all your Payment You have Br. remaining in payment ':"ያለዎትን ክፍያ በሙሉ ጨርሰዋል። በክፍያ የቀረው",
       'Please check to verify if all packages have arrived':"እባክዎ ሁሉም ጥቅሎች መድረሳቸውን ለማረጋገጥ ያረጋግጡ",
       'All packages have arrived':"ሁሉም ፓኬጆች ደርሰዋል",
       'Verified scan':"የተረጋገጠ ቅኝት",
       'Scan Qr code':"የQr ኮድ ይቃኙ",
       'You don\'t have any pending order.To make an order click the button below.':
"ምንም በመጠባበቅ ላይ ያለ ትእዛዝ የለዎትም። ለማዘዝ ከታች ያለውን አዝራር ጠቅ ያድርጉ።",
       'Status':"ሁኔታ",
       'Delivery Items':"የመላኪያ እቃዎች",
       'Pick up detail':"ዝርዝሩን አንሳ",
       'Floor':"ወለል",
       'with an elevator':"ከአሳንሰር ጋር",
       'With no elevator':"አሳንሰር በሌለበት",
       'Destination detail:':"የመድረሻ ዝርዝር",
       'Payment information:':"የክፍያ መረጃ",
       'Br.':"ብር.",
       'Paid':"የተከፈለ",
       'All paid':"ሁሉም ተከፍለዋል።",
       'not yet paid':"ገና አልተከፈለም",
       'There are no past orders in your history.':"በታሪክዎ ውስጥ ምንም ያለፉ ትዕዛዞች የሉም።",
       'Profile':"መገለጫ",
       'Your profile info':"የመገለጫዎ መረጃ",
       'Enter a valid first name':"ትክክለኛ ስም አስገባ",
       'Enter a valid last name':"ትክክለኛ የአያት ስም አስገባ",
       'Enter a valid phone number':"የሚሰራ ስልክ ቁጥር አስገባ",
       'Success!':"ስኬት!",
       'Sorry, an error occured, try again later':"ይቅርታ፣ ስህተት ተፈጥሯል፣ ቆይተው እንደገና ይሞክሩ",
       'Edit data':"Edit data",
       'Write your name':"ስምህን ጻፍ",
       'Name':"ስም",
       'Enter your email so we can reach you':"እርስዎን ለማግኘት እንድንችል ኢሜልዎን ያስገቡ",
       'your email':"ኢሜልዎ",
       'write the Subject':"ርዕሰ ጉዳዩን ይፃፉ",
       'Subject':"ርዕሰ ጉዳይ",
       'What can we help you with':"በምን እንረዳዎታለን",
       'write your message here':"መልእክትህን እዚህ ጻፍ",
       'Send':"ላክ",
       'Set Address and Pickup time':"አድራሻ እና የመውሰጃ ጊዜ ያዘጋጁ",
       'Search by location':"በቦታ ይፈልጉ",
       'Sorry, no luck':"ይቅርታ, ዕድል የለም",
       'Pick custom location':"ቦታ ይምረጡ",
       'pick':"መምረጥ",
       'Select a custom pick up location':"የመልቀሚያ ቦታ ይምረጡ",
       'Set the Date of pick up':"የሚወሰድበትን ቀን ያዘጋጁ",
       'Next':"ቀጥሎ",
       'Select a destination location':"የመድረሻ ቦታ ይምረጡ",
       'Set a Pickup date to proceed':"ለመቀጠል የመውሰጃ ቀን ያዘጋጁ",
       'Select a destination location and a Pickup date':"የመድረሻ ቦታ እና የመድረሻ ቀን ይምረጡ",
       'Submit':"አስገባ",
       'The total Distance is':"አጠቃላይ ርቀት ነው",
       'The total Duration of delivery is':"አጠቃላይ የማስረከቢያ ጊዜ ነው",
       'seconds':"ሰከንዶች",
       'Your Balance':"ያሎት ቀሪ ሂሳብ",
       'Your Card':"የእርስዎ ካርድ",
       'Deposit':"ተቀማጭ ገንዘብ",
       'Latest spendings':"የቅርብ ጊዜ ወጪዎች",
       'Deposit to wallet':"የኪስ ቦርሳዋ ላይ ገንዘብ ያስቀምጡ",
       'Buy card':"ካርድ ይግዙ",
       'How would you like to Deposit?':"እንዴት ተቀማጭ ማድረግ ይፈልጋሉ?",
       'You can choose to deposit to your wallet directly, or buy our van-card for a lesser fee':"በቀጥታ ወደ ቦርሳዎ ለማስገባት መምረጥ ወይም የቫን ካርዳችንን በትንሽ ክፍያ መግዛት ይችላሉ",
       'Account Holder':"የመለያ ባለቤት",
       'Expiration Date':"የመጠቀሚያ ግዜ",
       'Verify Email':"ኢሜል ያረጋግጡ",
       'A verification email has been sent to this email address':"የማረጋገጫ ኢሜይል ወደዚህ ኢሜይል አድራሻ ተልኳል",
       'Resend Email':"ኢሜይል እንደገና ላክ",
       'Cancel':"ሰርዝ",
       'Finish up with your payment':"ክፍያዎን ይጨርሱ",
       'Price':"ዋጋ",
       'Transport Cost':"የመጓጓዣ ዋጋ",
       'Packaging Cost':"የማሸጊያ ዋጋ",
       'Service charge with tax:':"የአገልግሎት ክፍያ ከግብር ጋር:",
       'How do you want to pay':"እንዴት መክፈል ይፈልጋሉ",
       'Pay from my wallet':"ከኪስ ቦርሳዬ ክፈል",
       'Pay on Pick Up':"በማንሳት ይክፈሉ",
       'Use Van it card':"የቫን ካርድ ይጠቀሙ",
       'VAN it':"ቫን ነው",
       'Enter Passcode':"የይለፍ ኮድ ያስገቡ",
       'Delete':"ሰርዝ",
       'Which service do you require?':"የትኛውን አገልግሎት ይፈልጋሉ?",
       'home':"ቤት",
       'Home Moving':"የቤት ተንቀሳቃሽ",
       'furniture':"የቤት እቃዎች",
       'Furniture Move':"የቤት ዕቃዎች ተንቀሳቃሽ",
       'company':"ኩባንያ",
       'Company Move':"የኩባንያ ተንቀሳቃሽ",
       'special':"ልዩ",
       'Special Move':"ልዩ ተንቀሳቃሽ",
        'Boxes':"ሳጥኖች",
       'Chair':"ወንበር",
       'Table':"ጠረጴዛ",
       'Bed':"አልጋ",
       'Bag':"ቦርሳ",
       'Small':"ትንሽ",
       'Medium':"መካከለኛ",
       'Large':"ትልቅ",
       'Huge':"ግዙፍ",
       'Box':"ሳጥን",
       'Sofa':"ሶፋ",
       'Book Shelf':"የመጽሐፍ መደርደሪያ",
       'Medium house package':"መካከለኛ የቤት እሽግ",
        'Sofa set':"የሶፋ ስብስብ",
       'Small house package':"አነስተኛ ቤት ጥቅል",
       'Vehicle: Mini-van':"ተሽከርካሪ: ሚኒ-ቫን",
       'Vehicle: Isuzu medium sized':"ተሽከርካሪ፡ አይሱዙ መካከለኛ መጠን ያለው",
       'Large house package':"ትልቅ የቤት እሽግ",
       'Vehicle: Enclosed Isuzu FSR':"ተሽከርካሪ: የተዘጋ አይሱዙ FSR",
       'Huge house package':"ግዙፍ የቤት ጥቅል",
       'Vehicle: Iveco':"ተሽከርካሪ: Iveco",
       'Home moving':"የቤት መንቀሳቀስ",
       'What other items did we miss':"ምን ሌሎች ነገሮች አምልጦናል።",
       'Other non-listed Items':"ሌሎች ያልተዘረዘሩ ዕቃዎች",
       'Has elevetor':"ሊፍት አለው",
      'What floor is the package at the Starting location?':"በመነሻ ቦታ ላይ ያለው ጥቅል ምን ወለል ነው?",
       'What floor is the package at Destination?':"መዳረሻ ላይ ያለው ጥቅሉ የትኛው ወለል ነው?",
      'Proceed':"ቀጥል",
      'Vehicle: Mini-van ':"ተሽከርካሪ: ሚኒ-ቫን ",
      'Vehicle: Enclosed Isuzu FSR ':"ተሽከርካሪ፡ የተዘጋ አይሱዙ FSR ",
      // ignore: equal_keys_in_map
      'Set the Date of pick up':"የሚወሰድበትን ቀን ያዘጋጁ",
      'Next':"ቀጥል",
      // ignore: equal_keys_in_map
      'Select a destination location':"የመድረሻ ቦታ ምረጥ",
      // ignore: equal_keys_in_map
      'Set a Pickup date to proceed':"ለመቀጠል የመውሰጃ ቀን ያዘጋጁ",
      'Select a destination location and a Pickup date ':"የመድረሻ ቦታ እና የመድረሻ ቀን ምረጥ ",

      'Order':"ማዘዝ",
      'Deposit to your wallet':"በኪስ ቦርሳዎ ላይ ተቀማጭ ያድርጉ",
      'Through which bank and their service do you like to complete the payment.':"ክፍያውን በየትኛው ባንክ እና በአገልግሎታቸው ማጠናቀቅ ይፈልጋሉ።",
      'We need your legal name for verification purposes':"ለማረጋገጫ ዓላማ ህጋዊ ስምዎን እንፈልጋለን",
      'How much would you like to deposit? *':"ምን ያህል ገንዘብ ማስገባት ይፈልጋሉ? *",
      'First name *':"የመጀመሪያ ስም *",
      'Middle name *':"የአባት ስም *",
      'Last name *':"የአያት ስም *",
      '1000 - 100,000 br.':"1000 - 100,000 ብር",
      'What is your legal First name?':"ህጋዊ የመጀመሪያ ስምህ ማን ነው?",
      'What is your legal Middle name?':"የእርስዎ ህጋዊ መካከለኛ ስም ማን ነው?",
      'What is your legal last name?':"ህጋዊ የአያት ስምህ ማን ነው?",
      'Enter a valid Amount to be deposited':"የሚቀመጥበትን ትክክለኛ መጠን ያስገቡ",
      'Enter a Valid legal name':"ትክክለኛ ህጋዊ ስም አስገባ",
      "**Follow all the instructions below.":"** ከዚህ በታች ያሉትን ሁሉንም መመሪያዎች ይከተሉ።",
      'We are not responsible for any inconviniences if the instructions are incorrectly followed**':"መመሪያዎቹ በስህተት ከተከተሉ ለሚፈጠረው ችግር ተጠያቂ አንሆንም**",
      '1) Choose any method Namely Manual/branch, Mobile banking or CBE birr to deposit/transfer.':"1) ለማስገባት/ለማስተላለፍ ማንኛውንም ዘዴ ማለትም ማንዋል/ቅርንጫፍ፣ሞባይል ባንክ ወይም ንግድ ባንክ ብር ይምረጡ።",
      '2) Deposit/transfer':"2) ተቀማጭ / ማስተላለፍ",
      'to account ':"ወደ ሂሳብ",
      '3) On the deposit form use the code below as a **Reason** this is very important.':"3) በተቀማጭ ፎርሙ ላይ ከዚህ በታች ያለውን ኮድ እንደ **ምክንያት *** ይህ በጣም አስፈላጊ ነው።",
      '4) Your Account will be updated to the deposited amount within the next 12 hours.':"4) በሚቀጥሉት 12 ሰዓታት ውስጥ መለያዎ ወደተቀማጭ ገንዘብ ይሻሻላል።",
      '5) The code is':"5) ኮድ ነው",
      'use this as Reason.':"ይህንን እንደ ምክንያት ይጠቀሙ ።",
      'Beware of Capitalization of the code.':"ከኮዱ አቢይነት ይጠንቀቁ።",
      'Hai This Is Full Screen Dialog':"ሃይ ይህ የሙሉ ስክሪን ንግግር ነው።",
      'DISMISS':"አሰናብት",
      'Your wallet':"የኪስ ቦርሳዎ",
      'An amount of ':"አንድ መጠን ",
      ' Br. will be deducted from your wallet':" ብር ከኪስ ቦርሳዎ ይቀነሳል።",
      'Agree to the terms of service':"በአገልግሎት ውሉ ይስማሙ",
      'Pay':"ይክፈሉ።",
      'Read this before you pay!':"ከመክፈልዎ በፊት ይህንን ያንብቡ!",
      'I have read and agree to the Terms':"ውሎቹን አንብቤ ተስማምቻለሁ",
      '1. Any change in Order or cancelation of the order should be done 4 hours prior to delivery We are not responsible for any misunderstanding after this set time In the event of such changes after the order a calculated price will be deducted from your van it account':"1. ማንኛውም የትዕዛዝ ለውጥ ወይም መሰረዝ ከመድረሱ 4 ሰአት በፊት መከናወን አለበት ከዚህ የተወሰነ ጊዜ በኋላ ለሚፈጠረው አለመግባባት ተጠያቂ አይደለንም ከትእዛዙ በኋላ እንደዚህ አይነት ለውጦች ሲከሰቱ የተሰላ ዋጋ ከእርስዎ የቫን ሒሳብ ላይ ይቆረጣል",
      'Finish your order by agreeing to these terms':"Finish your order by agreeing to these terms",
      'Account holder: ':"የመለያ ባለቤት:",
      'Your credits: ':"የእርስዎ ምስጋናዎች፡",
      'Enter the name on your card':"በካርድዎ ላይ ስሙን ያስገቡ",
      'Full name':"ሙሉ ስም",
      'What is the name on your card':"በካርድዎ ላይ ያለው ስም ማን ነው?",
      'The PIN':"ፒን",
      'Enter the PIN':"ፒኑን አስገባ",
      'the pin is a 4 digit number':"ፒን ባለ 4 አሃዝ ቁጥር ነው።",
      'Transaction completed':"ግብይት ተጠናቀቀ",
       '10000 Br. Credit Card for just 8,500 Br.':"10000 ብር. ክሬዲት ካርድ በ8,500 ብር ብቻ።",
      '30,000 Br. Credit Card for just 24,000 Br.':"30,000 ብር. ክሬዲት ካርድ በ24,000 ብር ብቻ",
      '50,000 Br. Credit Card for just 40,000 Br.':"50,000 ብር. ክሬዲት ካርድ በ40,000 ብር ብቻ",
      '100,000 Br. Credit Card for just 80,000 Br.':"100,000 ብር. ክሬዲት ካርድ በ80,000 ብር ብቻ",
      'Manual Pick-up':"በእጅ ማንሳት",
      'Go to wallet to deposit':"ለመያዝ ወደ ቦርሳ ሂድ",
      'Finish':"ጨርስ",
      '1. You must have amount of at least 1000 br. deposited in your Van wallet to request an order.':"1. ቢያንስ 1000 ብር መጠን ሊኖርዎት ይገባል. ትዕዛዝ ለመጠየቅ በቫን ቦርሳዎ ውስጥ ተቀምጧል",
      '- this amount will be reduced up on payment':"- ይህ መጠን በክፍያ ይቀንሳል",
      '2. You must Pay the required Amount in full upon pickup.':"2. ሲወስዱ የሚፈለገውን መጠን ሙሉ በሙሉ መክፈል አለቦት",
      '3. All payments should be done on time as agreed upon.':"3. ሁሉም ክፍያዎች በተስማሙት መሰረት በጊዜ መከናወን አለባቸው",
      '4. Any change in Order or cancelation of the order should be done 4 hours prior to delivery.':"4. ማንኛውም የትዕዛዝ ለውጥ ወይም መሰረዝ ከመድረሱ 4 ሰዓታት በፊት መደረግ አለበት",
      ' - We are not responsible for any misunderstanding after this set time':" - ከዚህ ከተወሰነ ጊዜ በኋላ ለሚፈጠረው አለመግባባት ተጠያቂ አይደለንም",
      ' - In the event of such changes after the order a calculated price will be deducted from your van it account':" - ከትዕዛዙ በኋላ እንደዚህ አይነት ለውጦች ሲከሰቱ የተሰላ ዋጋ ከእርስዎ ቫን it መለያ ላይ ተቀናሽ ይደረጋል",
      '5. Should there be any failure in payment':"5. በክፍያ ላይ ውድቀት ካለ",
      ' - Items to be delivered will be transported to our stores until further notice':" - የሚደርሱ ዕቃዎች እስከ ተጨማሪ ማስታወቂያ ድረስ ወደ መደብራችን ይጓጓዛሉ",
      ' - There will be an automatic freezing of the account and all the assets.':" - የመለያው እና የሁሉም ንብረቶች አውቶማቲክ ማቀዝቀዝ ይሆናል",
      ' - Any amount remaining in the wallet will be frozen until further notice.':" - በኪስ ቦርሳ ውስጥ የሚቀረው ማንኛውም መጠን እስከሚቀጥለው ማስታወቂያ ድረስ ይቀዘቅዛል",
      ' - An extended payment window will be provided, this will be the final extended date to be provided.':" - የተራዘመ የክፍያ መስኮት ይቀርባል፣ ይህ የሚቀርበው የመጨረሻው የተራዘመ ቀን ነው",
      ' 6. If the above agreement is not honered Van-it team will be forced to persue any legal action that would be deemed necessary':" 6. ከላይ የተጠቀሰው ስምምነት ካልተከበረ የቫን-አይት ቡድን አስፈላጊ ሆኖ የተገኘ ማንኛውንም ህጋዊ እርምጃ ለመውሰድ ይገደዳል",
      'Contact Us':"አግኙን",
      'Settings':"ቅንብሮች",
    },
    'Or_Et':{
      'Welcome Home':"Baga nagaan dhufte",
      'email':"iimeelii",
      'password':"jecha iccitii",
      'login':"seensa",
      'Setting':"Haala",
      'Home':"Mana",
      'wallet':"boorsaa xiqqoo",
      'Orders':"Ajaja",
      'Make an order':"Ajaja kenni",
      'Contact us':"Nu qunnamaa",
      'About us':"Waa'ee keenya",
      'Log Out':"Ba'i",
      'My Orders':"Ajaja Koo",
      'Current Order':"Tartiiba Ammaa",
      'Order history':"Seenaa tartiiba",
      'Track progress':"Adeemsa hordofaa",
      'Confirm cancellation':"Haqamuu mirkaneessi",
      'Confirm if you want to cancel this order':"Ajaja kana haquu yoo barbaadde mirkaneessi",
      'Confirm':"Mirkaneessuu",
      'I changed my mind':"Yaada koo jijjiireera",
      'Driver was late':"Konkolaachisaan harkifate",
      'The order was wrong':"Ajajni kenname dogoggora ture",
      'Some other reason':"Sababni biraa tokko tokko",
      'Enter a reason for canceling the order':"Sababni ajaja haquuf galchi",
      'Cancel order':"Ajaja haquu",
      'Delivery completed':"Geejjibni xumurame",
      'Before we conclude please finalize all required parts on this form':"Osoo hin xumurin dura kutaalee barbaachisan hunda unka kana irratti xumuraa",
      'Payment':"Kaffaltii",
      'You have concluded all your Payment You have Br. remaining in payment ':"Kaffaltii kee hunda xumurteetta Br. kaffaltii keessatti hafe ",
      'Please check to verify if all packages have arrived':"Maaloo paakeejiiwwan hundi dhufuu isaanii mirkaneessuuf ilaalaa",
      'All packages have arrived':"Paakeejiin hundi dhufeera",
      'Verified scan':"Skaan mirkanaa'e",
      'Scan Qr code':"Koodii QR sakatta'uu",
      'You don\'t have any pending order.To make an order click the button below.':"Ajaja eegamaa jiru hin qabdu.Ajaja gochuuf button armaan gadii cuqaasaa.",
      'Status':"Sadarkaa",
      'Status:':"Sadarkaa:",
      'Delivery Items':"Meeshaalee Geejjibaa",
      'Pick up detail':"Bal'inaan fudhadhu",
      'Floor':"Lafa",
      'with an elevator':"liftii waliin",
      'With no elevator':"Liftii hin qabne",
      'Destination detail:':"Ibsa bakka itti geessan:",
      'Payment information:':"Odeeffannoo kaffaltii:",

      'Paid':"Kaffalame",
      'All paid':"Hundi kaffalame",
      'not yet paid':"ammallee hin kaffalamiin",
      'There are no past orders in your history.':"Seenaa keessan keessatti ajajni darbe hin jiru.",
      'Profile':"Ibsama",
      'Your profile info':"Odeeffannoo piroofaayilii keessanii",
      'Enter a valid first name':"Maqaa jalqabaa sirrii ta'e galchi",
      'Enter a valid last name':"Maqaa dhumaa sirrii galchi",
      'Enter a valid phone number':"Lakkoofsa bilbilaa sirrii ta'e galchi",
      'Success!':"Milkaa'ina!",
      'Sorry, an error occured, try again later':"Dhiifama, dogongorri uumame, booda irra deebi'ii yaali",
      'Edit data':"Deetaa gulaali",
      'Write your name':"Maqaa kee barreessi",
      'Name':"Maqaa",
      'Enter your email so we can reach you':"Imeelii keessan galchaa akka isin bira ga'uuf",
      'your email':"email keessan",
      'write the Subject':"Mata duree barreessi",
      'Subject':"Mata duree",
      'What can we help you with':"Maal si gargaaruu dandeenya",
      'write your message here':"ergaa kee asitti barreessi",
      'Send':"Erguu",
      'Set Address and Pickup time':"Teessoo fi yeroo Fudhachuu Saagi",
      'Search by location':"Iddoodhaan barbaadi",
      'Sorry, no luck':"Dhiifama, carraa hin qabu",
      'Pick custom location':"Iddoo amala filadhu",
      'pick':"kaasuu",
      'Select a custom pick up location':"Iddoo fudhannaa amala filadhu",
      'Set the Date of pick up':"Guyyaa Fudhachuu Saagi",
      'Next':"Kan itti aanu",
      'Select a destination location':"Iddoo itti geessu filadhu",
      'Set a Pickup date to proceed':"Itti fufuuf guyyaa Fudhachuu saagi",
      'Select a destination location and a Pickup date':"Iddoo itti geessu fi guyyaa Fudhachuu filadhu",
      'Submit':"Galchuu",
      'The total Distance is':"Fageenyi waliigalaa",
      'The total Duration of delivery is':"Yeroon waliigalaa da'umsaa",
      'seconds':"sekondii",
      'Your Balance':"Madaallii Keessan",
      'Your Card':"Kaardii Keessan",
      'Deposit':"Kuusuu",
      'Latest spendings':"Baasii yeroo dhiyoo",
      'Deposit to wallet':"Kuufama gara boorsaa",
      'Buy card':"Kaardii bitachuu",
      'How would you like to Deposit?':"Akkamitti Deposit gochuu barbaadda?",
      'You can choose to deposit to your wallet directly, or buy our van-card for a lesser fee':"Kallattiin boorsaa keessanitti galchuu filachuu dandeessu, ykn kaffaltii xiqqaadhaan vaan-kaardii keenya bitachuu dandeessu",
      'Account Holder':"Abbaa Herregaa",
      'Expiration Date':"Guyyaa Dhuma",
      'Verify Email':"Imeelii Mirkaneessi",
      'A verification email has been sent to this email address':"Imeelii mirkaneessuu gara teessoo imeelii kanaatti ergameera",
      'Resend Email':"Imeelii Irra Deebiin Ergaa",
      'Cancel':"Haquu",
      'Finish up with your payment':"Kaffaltii kee xumuri",
      'Price':"Gatii",
      'Transport Cost':"Baasii Geejjibaa",
      'Packaging Cost':"Baasii Paakeejii",
      'Service charge with tax:':"Kaffaltii tajaajilaa gibira waliin:",
      'How do you want to pay':"Akkamitti kaffaluu barbaadda",
      'Pay from my wallet':"Boorsaa koo irraa kaffalaa",
      'Pay on Pick Up':"Kaffaltii Fudhachuu irratti",
      'Use Van it card':"Kaardii Van it fayyadamaa",
      'VAN it':"Koodii Dabarsaa Galchi",
      'Enter Passcode':"Koodii Dabarsaa Galchi",
      'Delete':"Haquu",
      'Which Service do you want':"Tajaajila kam barbaadda",
      'home':"mana",
      'Home Moving':"Mana Socho'uu",
      'furniture':"meeshaalee mana keessaa",
      'Furniture Move':"Sochii Meeshaalee Manaa",
      'company':"dhaabbata",
      'Company Move':"Sochii Dhaabbataa",
      'special':"kan adda ta'e",
      'Special Move':"Sochii Addaa",
      'Boxes':"Saanduqoota",
      'Chair':"Barcuma",
      'Table':"Minjaala",
      'Bed':"Siree",
      'Bag':"Korojoo",
      'Small':"Xiqqoo",
      'Medium':"Giddugaleessa",
      'Large':"Bal'aa",
      'Huge':"Guddaa",
      'Box':"Saanduqa",
      'Sofa':"Soofaa",
      'Book Shelf':"Sheelfii Kitaabaa",
      'Medium house package':"Paakeejii mana giddu galeessaa",
      'Sofa set':"Seet soofaa",
      'Small house package':"Paakeejii mana xiqqaa",
      'Vehicle: Mini-van':"Konkolaataa: Mini-van",
      'Vehicle: Isuzu medium sized':"Konkolaataa: Isuzu guddina giddu galeessaa",
      'Large house package':"Paakeejii mana guddaa",
      'Vehicle: Enclosed Isuzu FSR':"Konkolaataa: Isuzu FSR Cufame",
      'Huge house package':"Paakeejii mana guddaa",
      'Vehicle: Iveco':"Konkolaataa: Iveco",
      'Home moving':"Mana socho'uu",
      'What other items did we miss':"Meeshaalee biroo maaltu nu jalaa hafe",
      'Other non-listed Items':"Wantoota biroo hin tarreeffamne",
      'Has elevetor':"Liftii qaba",
      'What floor is the package at the Starting location?':"Paakeejiin bakka Jalqabaa jirutti daree akkamii qaba?",
      'What floor is the package at Destination?':"Paakeejiin Destination irratti argamu daree akkamii?",
      'Proceed':"Itti fufi",
      'Vehicle: Mini-van ':"Konkolaataa: Mini-van",
      'Vehicle: Enclosed Isuzu FSR ':"Konkolaataa: Isuzu FSR Cufame ",

      'Set the Date of pick up':"Guyyaa Fudhachuu Saagi",
      'Next':"Kan itti aanu",
      'Select a destination location':"Iddoo itti geessu filadhu",
      'Set a Pickup date to proceed':"Itti fufuuf guyyaa Fudhachuu saagi",
      'Select a destination location and a Pickup date ':"Iddoo itti geessu fi guyyaa Fudhachuu filadhu",
      'Order:':"Ajajuu:",
      'Deposit to your wallet':"Boorsaa keessanitti galchaa",
      'Through which bank and their service do you like to complete the payment.':"Kaffaltii kana karaa baankii fi tajaajila isaanii kamiin xumuruu jaallatta",
      'We need your legal name for verification purposes':"Maqaa seera qabeessa keessan mirkaneessuuf nu barbaachisa",
      'How much would you like to deposit? *':"Maallaqa meeqa galchuu barbaadda? *",
      'First name *':"Maqaa jalqabaa *",
      'Middle name *':"Maqaa giddu galeessaa *",
      'Last name *':"Maqaa akaakayyuu *",

      'What is your legal First name?':"Maqaan jalqabaa kee seera qabeessa maali?",
      'What is your legal Middle name?':"Maqaan Giddugaleessaa seera qabeessa ta'e maali?",
      'What is your legal last name?':"Maqaan dhumaa kee seera qabeessa maali?",
      'Enter a valid Amount to be deposited':"Hanga sirrii ta'e galchi",
      'Enter a Valid legal name':"Maqaa seeraa Sirrii Galchi",
      "**Follow all the instructions below.":"**Follow all the instructions below.",
      'We are not responsible for any inconviniences if the instructions are incorrectly followed**':"We are not responsible for any inconviniences if the instructions are incorrectly followed**",
      '1) Choose any method Namely Manual/branch, Mobile banking or CBE birr to deposit/transfer.':"1) Choose any method Namely Manual/branch, Mobile banking or CBE birr to deposit/transfer.",
      '2) Deposit/transfer':"2) Deposit/transfer",
      'to account ':"to account ",
      '3) On the deposit form use the code below as a **Reason** this is very important.':"3) On the deposit form use the code below as a **Reason** this is very important.",
      '4) Your Account will be updated to the deposited amount within the next 12 hours.':"4) Your Account will be updated to the deposited amount within the next 12 hours.",
      '5) The code is':"5) The code is",
      'use this as Reason.':"use this as Reason.",
      'Beware of Capitalization of the code.':"Beware of Capitalization of the code.",
      'Hai This Is Full Screen Dialog':"Hai This Is Full Screen Dialog",
      'DISMISS':"DISMISS",
      'Your wallet':"Your wallet",
      'An amount of ':"An amount of ",
      ' Br. will be deducted from your wallet':" Br. will be deducted from your wallet",
      'Agree to the terms of service':"Agree to the terms of service",
      'Pay':"Pay",
      'Read this before you pay!':"Read this before you pay!",
      'I have read and agree to the Terms':"I have read and agree to the Terms",
      '1. Any change in Order or cancelation of the order should be done 4 hours prior to delivery We are not responsible for any misunderstanding after this set time In the event of such changes after the order a calculated price will be deducted from your van it account':"1. Any change in Order or cancelation of the order should be done 4 hours prior to delivery We are not responsible for any misunderstanding after this set time In the event of such changes after the order a calculated price will be deducted from your van it account",
      'Finish your order by agreeing to these terms':"Finish your order by agreeing to these terms",
      'Account holder: ':"Account holder: ",
      'Your credits: ':"Your credits: ",
      'Enter the name on your card':"Enter the name on your card",
      'Full name':"Full name",
      'What is the name on your card':"What is the name on your card",
      'The PIN':"The PIN",
      'Enter the PIN':"Enter the PIN",
      'the pin is a 4 digit number':"the pin is a 4 digit number",
      'Transaction completed':"Transaction completed",
      '10000 Br. Credit Card for just 8,500 Br.':"10000 Br. Credit Card for just 8,500 Br.",
      '30,000 Br. Credit Card for just 24,000 Br.':"30,000 Br. Credit Card for just 24,000 Br.",
      '50,000 Br. Credit Card for just 40,000 Br.':"50,000 Br. Credit Card for just 40,000 Br.",
      '100,000 Br. Credit Card for just 80,000 Br.':"100,000 Br. Credit Card for just 80,000 Br.",
      'Manual Pick-up':"Manual Pick-up",
      'Go to wallet to deposit':"Go to wallet to deposit",
      'Finish':"Finish",
      '1. You must have amount of at least 1000 br. deposited in your Van wallet to request an order.':"1. You must have amount of at least 1000 br. deposited in your Van wallet to request an order.",
      '- this amount will be reduced up on payment':"- this amount will be reduced up on payment",
      '2. You must Pay the required Amount in full upon pickup.':"2. You must Pay the required Amount in full upon pickup.",
      '3. All payments should be done on time as agreed upon.':"3. All payments should be done on time as agreed upon.",
      '4. Any change in Order or cancelation of the order should be done 4 hours prior to delivery.':"4. Any change in Order or cancelation of the order should be done 4 hours prior to delivery.",
      ' - We are not responsible for any misunderstanding after this set time':" - We are not responsible for any misunderstanding after this set time",
      ' - In the event of such changes after the order a calculated price will be deducted from your van it account':" - In the event of such changes after the order a calculated price will be deducted from your van it account",
      '5. Should there be any failure in payment':"5. Should there be any failure in payment",
      ' - Items to be delivered will be transported to our stores until further notice':" - Items to be delivered will be transported to our stores until further notice",
      ' - There will be an automatic freezing of the account and all the assets.':" - There will be an automatic freezing of the account and all the assets.",
      ' - Any amount remaining in the wallet will be frozen until further notice.':" - Any amount remaining in the wallet will be frozen until further notice.",
      ' - An extended payment window will be provided, this will be the final extended date to be provided.':" - An extended payment window will be provided, this will be the final extended date to be provided.",
      ' 6. If the above agreement is not honered Van-it team will be forced to persue any legal action that would be deemed necessary':" 6. If the above agreement is not honered Van-it team will be forced to persue any legal action that would be deemed necessary",
      'Contact Us':"Contact Us",
      'Office desk':"Office desk",
      'Book shelf':"Book shelf",
      'Fragile electronics':"Fragile electronics",
      'premium':"premium",
      'Ultimate':"Ultimate",
      'Exclusive':"Exclusive",
      'Company moving':"Company moving",
      'Small company package':"Small company package",
      'Vehicles included: Mini-Isuzu ':"Vehicles included: Mini-Isuzu ",
      'This package includes upto:':"This package includes upto:",
      'Premium company package':"Premium company package",
      'Ulimate company package':"Ulimate company package",
      'Vehicle: Enclosed Isuzu FSR  ':"Vehicle: Enclosed Isuzu FSR  ",
      'Exclusive company package':"Exclusive company package",
      'Vehicle: Iveco ':"Vehicle: Iveco ",
      'Less than 2*2':"Less than 2*2",
      'less than 3*2':"less than 3*2",
      'less than 5*3':"less than 5*3",
    },
  'Tg_Et':{
  'Welcome Home':"እንዃዕ ብደሓን መጻእኩም",
  'email':"ኢሜይል",
  'password':"መሕለፊ ቓል",
  'login':"መእተዊ",
  'Setting':"ምድላው",
  'Home':"ናይ መጀመርታ ገጽ",
  'wallet':"ዋሌት",
  'Orders':"ትእዛዝ",
  'Make an order':"ትእዛዝ ግበር",
  'Contact us':"ምሳና ተራኸብ",
  'About us':"ብዛዕባና",
  'Log Out':"ኣውጽኣዮ",
  'My Orders':"ትእዛዘይ",
  'Current Order':"እዋናዊ ስርዓት",
  'Order history':"ታሪኽ ስርዓት",
  'Track progress':"ዕቤት ተከታተል",
  'Confirm cancellation':"ከም እተሰረዘ ኣረጋግጽ",
  'Confirm if you want to cancel this order':"ነዚ ትእዛዝ እዚ ኽትስርዞ እንተ ደሊኻ ኣረጋግጽ",
  'Confirm':"ኣረጋግጽ",
  'I changed my mind':"ሓሳበይ ለዊጠ",
  'Driver was late':"መራሕ ማኪና ደንጒዩ ነበረ",
  'The order was wrong':"እቲ ትእዛዝ ጌጋ እዩ ነይሩ",
  'Some other reason':"ካልእ ምኽንያት",
  'Enter a reason for canceling the order':"ነቲ ትእዛዝ እትስርዘሉ ምኽንያት ኣእቱ",
  'Cancel order':"ትእዛዝ ሰረዝ",
  'Delivery completed':"ዕለተ-ምብጻሕ ተዛዚሙ",
  'Before we conclude please finalize all required parts on this form':"ቅድሚ ምዝዛምና በጃኹም ንዅሉ እቲ ኣብዚ ፎርም እዚ ዘሎ ኣድላዪ ኽፋላት ዛዝሙ",
  'Payment':"ክፍሊት",
  'You have concluded all your Payment You have Br. remaining in payment ':"Paid? ኵሉ ኽፍሊትካ ኣብ መደምደምታ በጽሕኻ",
  'Please check to verify if all packages have arrived':"ኵሉ ጥቕላላት መጺኡ እንተ ዀይኑ ኣረጋግጹ",
  'All packages have arrived':"ኵሉ ጥቕላላት በጺሑ ኣሎ",
  'Verified scan':"እተረጋገጸ ስካን",
  'Scan Qr code':"ኮድ ስካን Qr'",
  'You don\'t have any pending order.To make an order click the button below.':"ገና ዘይተጸበየ ትእዛዝ የብልኩምን። ትእዛዝ ንምድላው ነዚ ኣብ ታሕቲ ዘሎ ጠውቕ",
  'Status':"ኵነታት",
  'Status:':"ኵነታት:",
  'Delivery Items':"ኣቕሑ ምብጻሕ",
  'Pick up detail':"ዝርዝር ሓበሬታ ኣልዕሉ",
  'Floor':"ደርቢ",
  'with an elevator':"ብሊፍት",
  'With no elevator':"ብዘይ ሊፍት",
  'Destination detail:':"ዝርዝር መበጽሕቲ:",
  'Payment information:':"ናይ ክፍሊት ሓበሬታ:",
  'Br.':"ብራ.",
  'Paid':"ከፊሉ",
  'All paid':"ኵሉ ኸፊሉ",
  'not yet paid':"ገና ኣይተኸፍለን",
  'There are no past orders in your history.':"ኣብ ታሪኽኩም ሕሉፍ ትእዛዝ የልቦን",
  'Profile':"ፕሮፌል",
  'Your profile info':"ናይ ፕሮፌሰር ሓበሬታኻ",
  'Enter a valid first name':"ቅኑዕ ስም ኣእቱ",
  'Enter a valid last name':"ቅኑዕ ስም ኣእቱ",
  'Enter a valid phone number':"ቅኑዕ ቍጽሪ ተሌፎን ኣእቱ",
  'Success!':"ኣሳልጦ!",
  'Sorry, an error occured, try again later':"ኣይትሓዘለይ ጌጋ ተጋግዩ ጸኒሕካ እንደገና ፈትን",
  'Edit data':"ሓበሬታ ኣዳሉ",
  'Write your name':"ስምካ ጽሓፍ",
  'Name':"ስም",
  'Enter your email so we can reach you':"ምእንቲ ኽንበጽሓካ ኢ-መይልካ ኣእቱ",
  'your email':"ኢ-መይልካ",
  'write the Subject':"ነቲ ርእሰ ነገር ጽሓፎ",
  'Subject':"ርእሰ ነገር",
  'What can we help you with':"እንታይ ክንሕግዘካ ንኽእል?",
  'write your message here':"መልእኽትኻ ኣብዚ ጽሓፍ",
  'Send':"ሰደድ",
  'Set Address and Pickup time':"ኣድራሻን ግዜ ንምልዓልን",
  'Search by location':"ብቦታ ድለዩ",
  'Sorry, no luck':"ኣይትሓዘለይ ዕድል የብ",
  'Pick custom location':"ናይ ልምዲ ቦታ ምረጹ",
  'pick':"ሕረ",
  'Select a custom pick up location':"ናይ ጉምሩክ ቦታ ኣልዕል",
  'Set the Date of pick up':"ዕለት ኣልዒልካ ምደብ" ,
  'Next':"ቀጺልና",
  'Select a destination location':"መዓርፎ ቦታ ምረጽ",
  'Set a Pickup date to proceed':"እትቕጽል ዕለት ምደብ",
  'Select a destination location and a Pickup date':"መዓርፎ ቦታን ዕለትን ምረጽ",
  'Submit':"ግዝኡ",
  'The total Distance is':"ጠቕላላ ርሕቐት እዩ",
  'The total Duration of delivery is':"ድምር ንውሓት ዕለተ ልደቱ እዩ",
  'seconds':"ሰከንድ",
  'Your Balance':"ሚዛንካ",
  'Your Card':"ካርድኻ",
  'Deposit':"ኣቐሚጥካ",
  'Latest spendings':"ናብ ቦርሳ ኣቐምጥ",
  'Deposit to wallet':"ናብ ቦርሳ ኣቐምጥ",
  'Buy card':"ካርድ ዓድግ",
  'How would you like to Deposit?':"ከመይ ጌርካ ኢኻ ኸተቐምጥ እትደሊ?",
  'You can choose to deposit to your wallet directly, or buy our van-card for a lesser fee':"ብቐጥታ ኣብ ቦርሳኻ ኸተቐምጦ ወይ ብሒደት ክፍሊት ናይ ማኪና ካርድና ኽትዕድግ ትኽእል ኢኻ",
  'Account Holder':"ሓላው ሕሳብ",
  'Expiration Date':"ዕለተ-መዛዘሚ",
  'Verify Email':"ኢ-መይል ኣረጋግጽ",
  'A verification email has been sent to this email address':"ናብዚ ኣድራሻ ኢ-መይል እዚ ናይ ምርግጋጽ ኢ-መይል ተላኢኹ ኣሎ",
  'Resend Email':"ኢ-መይል ለኣኽ",
  'Cancel':"ሰረዝ",
  'Finish up with your payment':"ብኽፍሊትካ ወድእ",
  'Price':"ዋጋ",
  'Transport Cost':"ዋጋ መጓዓዝያ",
  'Packaging Cost':"ዋጋ መሸጣ",
  'Service charge with tax:':"ግብሪ ዚኽፈል ክፍሊት ኣገልግሎት:",
  'How do you want to pay':"ከመይ ጌርካ ኢኻ ኽትከፍል እትደሊ?",
  'Pay from my wallet':"ካብ ቦርሳይ ክፈል",
  'Pay on Pick Up':"ኣልዒልካ ብምኽፋልካ",
  'Use Van it card':"ንቫን ኢት ካርድ ተጠቐመሉ",
  'VAN it':"ቫን ኢት",
  'Enter Passcode':"ፓስኮድ ኣእቱ",
  'Delete':"ኣጥፍኡ",
  'Which Service do you want':"ኣየነይቲ ኣገልግሎት ኢኻ እትደሊ?",
  'home':"ቤት",
  'Home Moving':"ናብ ቤት ምግዓዝ",
  'furniture':"ኣቕሑ ገዛ",
  'Furniture Move':"ኣቕሑ ገዛ ይንቀሳቐስ",
  'company':"ኩባንያ",
  'Company Move':"ናይ ኩባንያ ምንቅስቓስ",
  'special':"ፍሉይ",
  'Special Move':"ፍሉይ ምንቅስቓስ",
  'Boxes':"ሳጹናት",
  'Chair':"መንበር",
  'Table':"መኣዲ",
  'Bed':"ዓራት",
  'Bag':"ቦርሳ",
  'Small':"ንእሽቶ",
  'Medium':"ማእከላይ",
  'Large':"ገዚፍ",
  'Huge':"Huge",
  'Box':"ሳጹን",
  'Sofa':"ሶፍ",
  'Book Shelf':"መደርደሪ መጽሓፍ",
  'Medium house package':"ማእከላይ ገዛ ፓኬጅ",
  'Sofa set':"ናይሶፋ ስብስብ",
  'Small house package':"ንእሽቶ ገዛ ፓኬጅ",
  'Vehicle: Mini-van':"ተሽከርካሪት: ሚኒ-ቫን",
  'Vehicle: Isuzu medium sized':"መኪና: ኢሱዙ ማእከላይ ስፍሓት",
  'Large house package':"ዓቢ ገዛ ፓኬጅ",
  'Vehicle: Enclosed Isuzu FSR':"ተሽከርካሪት: ዕጹው ኢሱዙ FSR",
  'Huge house package':"ዓቢ ገዛ ፓኬጅ",
  'Vehicle: Iveco':"መኪና:Iveco",
  'Home moving':"ገዛ ምግዓዝ",
  'What other items did we miss':"ካልእ እንታይ ዓይነት ኣቑሑት ኣምሊጡና።",
  'Other non-listed Items':"ካልኦት ዘይተዘርዘሩ ነገራት",
  'Has elevetor':"ሊፍት ኣለዎ",
  'What floor is the package at the Starting location?':"ኣብ መበገሲ ቦታ ዘሎ ፓኬጅ እንታይ ደርቢ እዩ?",
  'What floor is the package at Destination?':"ኣብ መዕለቢ እንታይ ደርቢ እዩ እቲ ፓኬጅ?",
  'Proceed':"ቀጽል",
  'Vehicle: Mini-van ':"ተሽከርካሪት: Mini-van ",
  'Vehicle: Enclosed Isuzu FSR ':"መኪና: ዕጹው Isuzu FSR ",
  // ignore: equal_keys_in_map
  'Set the Date of pick up':"ዕለት ምልዓል ኣቐምጥ",
  'Next':"ቀጺሉ",
  // ignore: equal_keys_in_map
  'Select a destination location':"መዕለቢ ቦታ ምረጽ",
  // ignore: equal_keys_in_map
  'Set a Pickup date to proceed':"ንኽቕጽል ዕለት ምውሳድ ኣቐምጥ",
  'Select a destination location and a Pickup date ':"መዕለቢ ቦታን Pickup dateን ምረጽ ",

  'Order:':"ትእዛዝ:",
  'Deposit to your wallet':"ኣብ ቦርሳኻ ኣቐምጥ",
  'Through which bank and their service do you like to complete the payment.':"በየናይ ባንክን ኣገልግሎቶምን ኣቢልካ እቲ ክፍሊት ክትውድእ ትፈቱ",
  'We need your legal name for verification purposes':"ንዕላማ ምርግጋጽ ሕጋዊ ስምካ የድልየና'ዩ",
  'How much would you like to deposit? *':"‘ክንደይ ገንዘብ ከተቐምጥ ምደለኻ? *",
  'First name *':"ሽም ናይ በአልካ *",
  'Middle name *':"ሽም ናይ ኣቦ*",
  'Last name *':"ሽም አቦህጎ *",
  '1000 - 100,000 br.':"1000 - 100,000 ቅርሺ",
  'What is your legal First name?':"ሕጋዊ ናይ በአልካ እንታይ እዩ?",
  'What is your legal Middle name?':"ሕጋዊ ሽም ናይ ኣቦ እንታይ እዩ?",
  'What is your legal last name?':"ሕጋዊ ሽም አቦህጎ እንታይ እዩ ?",
  'Enter a valid Amount to be deposited':"ክቕመጥ ዘለዎ ቅኑዕ መጠን ገንዘብ ኣእቱ",
  'Enter a Valid legal name':"ቅኑዕ ሕጋዊ ስም ኣእቱ",
  "**Follow all the instructions below.":"**ኣብ ታሕቲ ዘሎ ኩሉ መምርሒታት ተኸተል።",
  'We are not responsible for any inconviniences if the instructions are incorrectly followed**':"እቲ መምርሒ ብጌጋ እንተተኸቲሉ ንዝኾነ ይኹን ምዝንጋዕ ተሓታቲ ኣይንኸውንን**",
  '1) Choose any method Namely Manual/branch, Mobile banking or CBE birr to deposit/transfer.':"1) ዝኾነ ይኹን ኣገባብ ምምራጽ ማለት ማንዋል/ጨንፈር፣ ሞባይል ባንኪ ወይ ሲቢኢ ብር ንምቕማጥ/ዝሰጋገር።",
  '2) Deposit/transfer':"2) ምቕማጥ/ምትሕልላፍ'",
  'to account ':"ናብ ሂሳብ",
  '3) On the deposit form use the code below as a **Reason** this is very important.':"3) ኣብቲ ናይ ምቕማጥ ቅጥዒ ኣብ ታሕቲ ዘሎ ኮድ ከም **ምኽንያት** ተጠቐሙ እዚ ኣዝዩ ኣገዳሲ እዩ።",
  '4) Your Account will be updated to the deposited amount within the next 12 hours.':"4) ሕሳብኩም ኣብ ውሽጢ ዝቕፅሉ 12 ሰዓታት ናብቲ ዝተቐመጠ መጠን ገንዘብ ክመሓየሽ እዩ።",
  '5) The code is':"5) እቲ ኮድ",
  'use this as Reason.':"እዚ ከም ምኽንያት ተጠቐመሉ። ።",
  'Beware of Capitalization of the code.':"ካብ ርእሰ-ጽሑፍ ናይቲ ኮድ ተጠንቀቑ።",
  'Hai This Is Full Screen Dialog':"ሃይ እዚ ምሉእ ስክሪን ዝርርብ",
  'DISMISS':"ምእላይ",
  'Your wallet':"ናይ ጁባ ቦርሳኻ",
  'An amount of ':"ብዝሒ ናይ ",
  ' Br. will be deducted from your wallet':" ብ. ካብ ቦርሳኻ ክቑረጽ እዩ",
  'Agree to the terms of service':"ኣብ ውዕል ኣገልግሎት ተሰማምዑ",
  'Pay':"ክፈል።",
  'Read this before you pay!':"ቅድሚ ምኽፋልካ ነዚ ኣንብቦ!",
  'I have read and agree to the Terms':"እቲ ውዕላት ኣንቢበን ተሰማሚዐሉን እየ",
  '1. Any change in Order or cancelation of the order should be done 4 hours prior to delivery We are not responsible for any misunderstanding after this set time In the event of such changes after the order a calculated price will be deducted from your van it account':"1. ዝኾነ ይኹን ለውጢ ኣብ ትእዛዝ ወይ ምስራዝ ትእዛዝ ቅድሚ ምብጻሕ 4 ሰዓታት ክግበር ኣለዎ ድሕሪ እዚ ዝተወሰነ ግዜ ንዝፍጠር ዝኾነ ይኹን ዘይምርድዳእ ተሓተትቲ ኣይኮናን ድሕሪ ትእዛዝ ከምዚ ዓይነት ለውጢ እንተጋጢሙ ዝተቖጽረ ዋጋ ካብ ቫን ኢት ሕሳብኩም ክቑረጽ እዩ",
  'Finish your order by agreeing to these terms':"ነዞም ውዕላት ብምስምማዕ ትእዛዝኩም ውድእ",
  'Account holder: ':"ወናኒ ሕሳብ:",
  'Your credits: ':"ክሬዲትካ:",
  'Enter the name on your card':"ነቲ ኣብ ካርድኻ ለሎ ሽም ኣእትዎ",
  'Full name':"ምሉእ ሽም",
  'What is the name on your card':"እቲ ኣብ ካርድኻ ዘሎ ሽም እንታይ እዩ?",
  'The PIN':"ፒን",
  'Enter the PIN':"ዝ ፒኑ ኣእቱ",
  'the pin is a 4 digit number':"እቲ ፒን 4 ቍጽሪ እ።",
  'Transaction completed':"ንግዳዊ ልውውጥ ተዛዚሙ",
  '10000 Br. Credit Card for just 8,500 Br.':"10000 ቅርሺ ክሬዲት ካርድ ብ8,500 ቅርሺ ክሬዲት ካርድ በ8,500 ብር ብቻ።",
  '30,000 Br. Credit Card for just 24,000 Br.':"30,000 ቅርሺ ክሬዲት ካርድ ብ24,000 ቅርሺ ክሬዲት ካርድ በ24,000 ብር ብቻ",
  '50,000 Br. Credit Card for just 40,000 Br.':"50,000 ቅርሺ ክሬዲት ካርድ ብ40,000 ቅርሺ ክሬዲት ካርድ በ40,000 ብር ብቻ",
  '100,000 Br. Credit Card for just 80,000 Br.':"100,000 ቅርሺ ክሬዲት ካርድ ብ80,000 ቅርሺ ክሬዲት ካርድ በ80,000 ብር ብቻ",
  'Manual Pick-up':"Manual ፒክ-ኣፕ",
  'Go to wallet to deposit':"ክትእክቦ ናብ ቦርሳ ኺድ",
  'Finish':"ዝዛዘም",
  '1. You must have amount of at least 1000 br. deposited in your Van wallet to request an order.':"1. ትእዛዝ ንምሕታት እንተ ወሓደ 1000 ቅርሺ ኣብ ቦርሳኻ ኣቐሚጥካ ኽትከውን ኣሎካ።",
  '- this amount will be reduced up on payment':"- እዚ መጠን እዚ ብኽፍሊት ኪንኪ እዩ",
  '2. You must Pay the required Amount in full upon pickup.':"2. ነቲ ዚድለ መጠን ገንዘብ ኣብ ማኪናኻ ምሉእ ብምሉእ ክትከፍሎ ኣሎካ።",
  '3. All payments should be done on time as agreed upon.':"3. ኵሉ እቲ ኽፍሊት ከምቲ እተሰማማዕካሉ ኣብ ሰዓቱ ኺግበር ኣለዎ።",
  '4. Any change in Order or cancelation of the order should be done 4 hours prior to delivery.':"4. ዝዀነ ይኹን ኣብ ስርዓት ለውጢ ወይ ምፍራስ እቲ ትእዛዝ ቅድሚ ምብጻሕ 4 ሰዓት ኣቐዲሙ ኺግበር ኣለዎ።",
  ' - We are not responsible for any misunderstanding after this set time':" - ድሕሪ እዚ ዝተቐመጠ ግዜ ዝኾነ ይኹን ዘይምርድዳእ ተሓተትቲ ኣይኮንናን።",
  ' - In the event of such changes after the order a calculated price will be deducted from your van it account':" - ድሕሪ ትእዛዝ ከምዚ ዓይነት ለውጢ እንተጋጢሙ ዝተቖፀረ ዋጋ ካብ ቫን ኢት ሕሳብኩም ይቑረፅ'፤",
  '5. Should there be any failure in payment':"5.ኣብ ክፍሊት ዝኾነ ውድቀት ክህሉ ኣለዎ ድዩ",
  ' - Items to be delivered will be transported to our stores until further notice':" -ክበጽሑ ዘለዎም ኣቑሑት ክሳብ ተወሳኺ ምልክታ ናብ ድኳናትና ክጓዓዙ እዮም",
  ' - There will be an automatic freezing of the account and all the assets.':" - ኣውቶማቲክ ምዕጋት ናይቲ ሕሳብን ኩሉ ንብረትን ክህሉ እዩ።",
  ' - Any amount remaining in the wallet will be frozen until further notice.':" - ዝኾነ ኣብ ቦርሳ ዝተረፈ መጠን ገንዘብ ክሳብ ተወሳኺ ምልክታ ክዕጾ እዩ።",
  ' - An extended payment window will be provided, this will be the final extended date to be provided.':" - ዝተናውሐ ናይ ክፍሊት መስኮት ክቐርብ እዩ፣ እዚ ናይ መወዳእታ ዝተናውሐ ዕለት ክቐርብ እዩ። ",
  ' 6. If the above agreement is not honered Van-it team will be forced to persue any legal action that would be deemed necessary':" 6. እዚ ኣብ ላዕሊ ዝተጠቕሰ ስምምዕ እንተዘይተኸቢሩ ጋንታ ቫን-ኢት ኣድላዪ ኮይኑ ዝረአ ዝኾነ ይኹን ሕጋዊ ስጉምቲ ክትወስድ ትግደድ።",
  'Contact Us':"ምሳና ተራኸብ",
  'Status:':"ኩነታቱ:",
  'Office desk':"ናይ ቤት ጽሕፈት ሰደቓ",
  'Book shelf':"መጽሓፍ መደርደሪ",
  'Fragile electronics':"ተሰባሪ ኤለክትሮኒካዊ መሳርሒታት",
  'premium':"ፕሪሚየም",
  'Ultimate':"መወዳእታ",
  'Exclusive':"ንበይንኻ",
  'Company moving':"ኩባንያ ምግዓዝ",
  'Small company package':"ንእሽቶ ኣቕሓ ኩባንያ",
  'Vehicles included: Mini-Isuzu ':"እተን ማካይን - ሚኒ-ኢሱዙ ",
  'This package includes upto:':"እዚ ጥቕላል እዚ ንኸምዚ ዝስዕብ ዘጠቓልል ኢዩ",
  'Premium company package':"ፕሪምዩም ኩባንያ ፓኬጅ",
  'Ulimate company package':"ናይ መወዳታ ኩባንያ ፓኬጅ",
  'Vehicle: Enclosed Isuzu FSR  ':"ብሽክለታ - እተዓጽወ Isuzu FSR",
  'Exclusive company package':"ፍሉይ ናይ ኩባንያ ጥቕላል",
  'Vehicle: Iveco ':"ተሽከርካሪ : ኢቭኮ",
  'Less than 2*2':"ካብ 2*2 ንታሕቲ",
  'less than 3*2':"ካብ 3*2 ንታሕቲ",
  'less than 5*3':"ካብ 5*3 ንታሕቲ",
}
  };
}